server:
  port: 8888
# cloud location having configuration file
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Seema1995/spring-cloud-microservices-datasource.git

          