server:
  port: 5555
spring:
  application:
    name: zuul-app
    
# register zuul proxy server in eureka server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    
#actuator end points to see routes of api gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
# configuring the routes for microservice

zuul:
  ignored-services: "*"
  prefix: /api
  routes:
    secondapp: /second-app/**
    firstapp: /first-app/**
  
  
